version: '3.8'

services:
  akeneo:
    image: websoft9dev/akeneo:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - ${APP_HTTP_PORT}:80
    volumes:
      - akeneo:/var/www/html
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    restart: always
    environment:
      AKENEO_MYSQL_DATABASE: ${DB_MYSQL_NAME}
      AKENEO_MYSQL_USER: ${DB_MYSQL_USER}
      AKENEO_MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      AKENEO_MYSQL_HOST: ${DB_MYSQL_HOST}
      AKENEO_SITENAME: ${APP_SITENAME}
      AKENEO_ADMIN_USER: ${APP_ADMIN_NAME}
      AKENEO_ADMIN_PASSWORD: ${APP_ADMIN_PASSWORD}
      
  mysql:
    image: mysql:${DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-mysql
    restart: always
    ports:
     - ${DB_MYSQL_PORT}:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:${DB_ES_VERSION}'
    container_name: ${APP_NAME}-elasticsearch
    restart: always
    environment:
      ES_JAVA_OPTS: '${ES_JAVA_OPTS:--Xms512m -Xmx512m}'
      discovery.type: 'single-node'
    ports:
      - '${DB_ES_PORT}:9200'


networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  akeneo:
  mysql:
