name: contentful automic backup

on: 
#   push
   workflow_dispatch
  # schedule:
  # - cron: "0 12 * * 5"

jobs:
  export:
    runs-on: ubuntu-latest
    outputs:
      op_setup:   ${{ steps.conclusion.outputs.setup }}
      op_install: ${{ steps.conclusion.outputs.install }}
      op_export:  ${{ steps.conclusion.outputs.export }} 
      op_push:    ${{ steps.conclusion.outputs.push }}
      op_backup:  ${{ steps.conclusion.outputs.backup }}
      
    steps:
      - uses: actions/checkout@master
      


        
        
        
        
        
