name: contentful automic backup

on: 
#   push
   workflow_dispatch
  # schedule:
  # - cron: "0 12 * * 5"

jobs:
  export:
  
    runs-on: ubuntu-latest
    
    outputs:
      op_setup:   ${{ steps.conclusion.outputs.setup }}
      op_install: ${{ steps.conclusion.outputs.install }}
      op_export:  ${{ steps.conclusion.outputs.export }} 
      op_push:    ${{ steps.conclusion.outputs.push }}
      op_backup:    ${{ steps.conclusion.outputs.backup }}
      
    steps:
      - uses: actions/checkout@master
      
      - name: setup node.js environment
      - id: setup
        uses: actions/setup-node@v3.5.1
      
      - name: install contentful cli
      - id: install
        run: npm install -g contentful-cli
        
      - name: export data        
      - id: export
        run: |
          export_date=`date +%Y-%m-%d`
          mkdir contentful/${export_date}
          contentful space export --config contentful/export-config.json --export-dir contentful/${export_date}/ --error-log-file contentful/${export_date}/error.json --mt ${{ secrets.Contentful_Export_Token }}
          
      - name: push data             
      - id: push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "push the contenful backup file"
          
      - name: output the result of the job to the send email job
      - id: conclusion
        run: |
         echo "setup   =${steps.setup.conclusion}"  >> $GITHUB_OUTPUT
         echo "install =${steps.installconclusion}" >> $GITHUB_OUTPUT
         echo "export  =${steps.export.conclusion}" >> $GITHUB_OUTPUT
         echo "push    =${steps.push.conclusion}"   >> $GITHUB_OUTPUT
         [ -f contentful/${export_date}/error.json ]  && echo "backup=failure" >> $GITHUB_OUTPUT || echo "backup=success" >> $GITHUB_OUTPUT      


  send-email:
    if: ${{ always() }}
    needs: export
    runs-on: ubuntu-latest
    steps:
      
      - name: edit the email content out of the export job output
        run: |
         if [ ${{ needs.export.outputs.op_setup }} ]
         then 
          echo "subject='[ERROR]Contentful backup inform'" >> $GITHUB_ENV
          echo "body='setup node.js environment Command execution error'" >> $GITHUB_ENV
          echo "attachments = ''" >> $GITHUB_ENV 
          
         elif [ ${{ needs.export.outputs.op_install }} ]
         then 
          echo "subject='[ERROR]Contentful backup inform'" >> $GITHUB_ENV
          echo "body='install contentful cli Command execution error'" >> $GITHUB_ENV
          echo "attachments = ''" >> $GITHUB_ENV 
          
         elif [ ${{ needs.export.outputs.op_export }} ]
         then 
          echo "subject='[ERROR]Contentful backup inform'" >> $GITHUB_ENV
          echo "body='Contentful Export Command execution error'" >> $GITHUB_ENV
          echo "attachments = ''" >> $GITHUB_ENV 
          
         elif [ ${{ needs.export.outputs.op_push }} ]
         then 
          echo "subject='[ERROR]Contentful backup inform'" >> $GITHUB_ENV
          echo "body='Push Data Command execution error'" >> $GITHUB_ENV        
          echo "attachments = ''" >> $GITHUB_ENV    
          
         elif [ ${{ needs.export.outputs.op_error }} ]
         then 
          echo "subject='[ERROR]Contentful backup inform'" >> $GITHUB_ENV
          echo "body='install contentful cli failure'" >> $GITHUB_ENV
          echo "attachments = contentful/${{ env.export_date }}/error.json" >> $GITHUB_ENV
          
         else
         then 
          echo "subject='[ERROR]Contentful backup inform'" >> $GITHUB_ENV
          echo "body='install contentful cli failure '" >> $GITHUB_ENV
          echo "attachments = contentful/${{ env.export_date }}/export.json" >> $GITHUB_ENV 
          
         fi
        
      - name: Send inform mail
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: ${env.subject}
          body: ${env.body}
          attachments: ${env.attachmentss}
          to: 2983604867@qq.com
          from: GitHub Actions

        
        
        
        
        
