name: contentful automic backup

on: 
#   push
   workflow_dispatch
  # schedule:
  # - cron: "0 12 * * 5"

jobs:
  export:
    runs-on: ubuntu-latest
    outputs:
      op_setup:   ${{ steps.conclusion.outputs.setup }}
      op_install: ${{ steps.conclusion.outputs.install }}
      op_export:  ${{ steps.conclusion.outputs.export }} 
      op_push:    ${{ steps.conclusion.outputs.push }}
      op_backup:  ${{ steps.conclusion.outputs.backup }}
      
    steps:
      - uses: actions/checkout@master
 
      - id: setup
        uses: actions/setup-node@v3.5.1
      
      - id: install
        run: npm install -g contentful-cli
           
      - id: export
        run: |
          export_date=`date +%Y-%m-%d`
          mkdir contentful/${export_date}
          contentful space export --config contentful/export-config.json --export-dir contentful/${export_date}/ --error-log-file contentful/${export_date}/error.json --mt ${{ secrets.Contentful_Export_Token }}
                     
      - id: push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "push the contenful backup file"
          
      - id: conclusion
        run: |
         echo "setup   =${steps.setup.conclusion}"  >> $GITHUB_OUTPUT
         echo "install =${steps.installconclusion}" >> $GITHUB_OUTPUT
         echo "export  =${steps.export.conclusion}" >> $GITHUB_OUTPUT
         echo "push    =${steps.push.conclusion}"   >> $GITHUB_OUTPUT
         [ -f contentful/${export_date}/error.json ]  && echo "backup=failure" >> $GITHUB_OUTPUT || echo "backup=success" >> $GITHUB_OUTPUT      


        
        
        
        
        
