name: contentful automic backup

on: 
#   push
   workflow_dispatch
  # schedule:
  # - cron: "0 12 * * 5"

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        
      - name: install contentful-cli
        run: npm install -g contentful-cli
        
      - name: export contentful data
        run: |
          export_date=`date +%Y-%m-%d-%H-%M-%S`
          mkdir contentful/${export_date}
          contentful space export --config contentful/export-config.json --export-dir contentful/${export_date}/ --error-log-file contentful/${export_date}/error.json
  
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "push the contenful backup file"

      
  send-email:
    runs-on: ubuntu-latest
    needs: export
    steps:
      - uses: actions/checkout@master
      - name: test the file is pushed success or not
        run: |
          export_date=`date +%Y-%m-%d-%H-%M-%S`
          [ -f contentful/${export_date}/error.json ] && echo "hasErrorFile=yes" >> $GITHUB_ENV || echo "hasErrorFile=no" >> $GITHUB_ENV
          [ -f contentful/${export_date}/export.json ] && echo "hasExportFile=yes" >> $GITHUB_ENV || echo "hasExportFile=no" >> $GITHUB_ENV
          echo "${{ env.hasErrorFile }}"
	  echo "${{ env.hasExportFile }}"

      - name: Send backup success mail
        uses: dawidd6/action-send-mail@master
        if: contains(hasExportFile,'yes') && contains(hasErrorFile,'no')
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "[SUCCESS]Contentful backup inform"
          body: contentful timely backup has done,The file is attached.
          attachments: contentful/${{ env.export_date }}/export.json
          to: 2983604867@qq.com
          from: GitHub Actions
        
      - name: Send push error inform mail
        uses: dawidd6/action-send-mail@master
        if: contains(hasExportFile,'no') && contains(hasErrorFile,'no')
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "[PUSH ERROR]Contentful backup inform"
          body: when push the file to the repository,there are some errors happened.
          to: 2983604867@qq.com
          from: GitHub Actions  

      - name: Send backup error inform mail
        uses: dawidd6/action-send-mail@master
        if: contains(hasErrorFile,'yes')
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "[BACUP ERROR]Contentful backup inform"
          body: when excute the code of exporting contentful data ,there are some errors happened.
          attachments: contentful/${{ env.export_date }}/error.json
          to: 2983604867@qq.com
          from: GitHub Actions

        
        
        
        
        
