name: 
  contentful automic backup

on: 
  workflow_dispatch

jobs:
  build:
    runs-on: 
      ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        
      - name: install contentful-cli
        run: npm install -g contentful-cli
        
      - name: export contentful data
        run: |
          export_date=`date +%Y-%m-%d_%H:%M:%S`
          contentful space export --config contentful/export-config.json --content-file "export_${export_date}.json" --error-log-file ./contentful/error_${export_date}.json
          
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Contentful backup error inform
          body: file://email.txt
          to: shenkebug@qq.com
          from: GitHub Actions
          content_type: text/plain

          
      - name: commit data
        run: |
          git config --global user.email 2983604867@qq.com
          git config --global user.name zl-go
          git add .
          git commit -m "push the contenful backup file test" -a

      - name: Push changes
        run: |
          git push origin main
          
