name: contentful automic backup

on: 
  push
#   workflow_dispatch
  # schedule:
  # - cron: "0 12 * * 5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        
      - name: install contentful-cli
        run: npm install -g contentful-cli
        
      - name: export contentful data
        run: |
          export_date=`date +%Y-%m-%d`
          mkdir contentful/${export_date}
          contentful space export --config contentful/export-config.json --export-dir contentful/${export_date}/ --error-log-file contentful/${export_date}/error.json
          echo "export_date=$export_date" >> $GITHUB_ENV
          [ -f contentful/${export_date}/error.json ] && echo "isError=yes" >> $GITHUB_ENV || echo "isError=no" >> $GITHUB_ENV
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "push the contenful backup file"

      # add Actions secrets:Settings->Secret->Actions->New repository secret
      # MAIL_PASSWORD: mail SMTP code
      - name: Send error inform mail
        uses: dawidd6/action-send-mail@master
        if: contains(env.isError, 'yes')
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Contentful backup error inform
          body: there is some error when contentful data export
          attachments: contentful/${{ env.export_date }}/error.json
          to: 2983604867@qq.com
          from: GitHub Actions
          
          
          
#   test-push:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
      
#       - name: Setup Node.js environment
#         run: |
#           export_date=`date +%Y-%m-%d`
#           [ -f contentful/${export_date}/export.json ] && echo "isError=yes" >> $GITHUB_ENV || echo "isError=no" >> $GITHUB_ENV
          
#       # add Actions secrets:Settings->Secret->Actions->New repository secret
#       # MAIL_PASSWORD: mail SMTP code
#       - name: Send error inform mail
#         uses: dawidd6/action-send-mail@master
#         if: contains(env.isError, 'no')
#         with:
#           server_address: smtp.qq.com
#           server_port: 465
#           username: ${{ secrets.MAIL_USERNAME }}
#           password: ${{ secrets.MAIL_PASSWORD }}
#           subject: Contentful backup error inform
#           body: file://contentful/${{ env.export_date }}/export.json
#           to: 2983604867@qq.com
#           from: GitHub Actions  
        
        
        
        
        
        
