name: Docker Build And Push To Docker Hub

on:
  push:
    branches: [ main ]
    paths: 
      - 'apps/*/Dockerfile'
      - 'apps/*/cmd.sh'
      - 'apps/*/entrypoint.sh'
    tags:
      - v**
jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    env:
      TAGS: latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
         
      - id: files-1
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done 
          
      - name: new file
        run: |
          mkdir test
          cd test
          touch test.txt
          
      - id: files-2
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done
          
      - id: push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "push the contenful backup file"    
          
          
      - id: files-3
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done
