name: Docker Build And Push To Docker Hub

on:
  push:
    branches: [ main ]
    paths: 
      - 'apps/*/Dockerfile'
      - 'apps/*/cmd.sh'
      - 'apps/*/entrypoint.sh'
    tags:
      - v**
jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    env:
      TAGS: latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - name: git log
        run: |
          git log --stat
          git log | grep -o 'commit .*' | awk -F" " '{print $2}' | git diff-tree --no-commit-id --name-only -r
