name: Docker Build And Push To Docker Hub

on:
  push:
    branches: [ main ]
    paths: 
      - 'apps/*/Dockerfile'
      - 'apps/*/cmd.sh'
      - 'apps/*/entrypoint.sh'
    tags:
      - v**
jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    env:
      TAGS: latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
         
      - uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'    
          
      - name: new file
        run: |
          mkdir testFile
          touch test.txt
          
      - uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'   
          
      - id: push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "push the contenful backup file"    
          
          
      - uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'   
