name: contentful cli import data

on:
  workflow_dispatch
  
jobs:
  import:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
 
      - name: setup node.js environment
        uses: actions/setup-node@v3.5.1
      
      - name: install contentful cli
        run: npm install -g contentful-cli
        
      - name: import data
        run: |
          contentful space import --config contentful/import-config.json --mt ${{secrets.CONTENTFUL_EXPORT_TOKEN}} --content-file contentful/2022-10-26/export.json
          
          
      - id: push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "push the error backup file"
        
      
