name: contentful automic backup
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
      - name: install contentful cli
        run: npm install -g contentful-cli
      - name: create a variable export-date
        run: export-date='date +%Y%m%d'
      - name: export contentful data
        run: contentful space export --config contentful/export-config.json --content-file export${export-date}
