name: contentful automic backup
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
      - name: install contentful cli
        run: npm install -g contentful-cli
      - name: create a variable date
        run: |
          fee_date=`date +%Y-%m-%d`
          echo $fee_date
      - name: export contentful data
        run: contentful space export --config contentful/export-config.json --content-file 'export_${fee_date}'
