name: contentful automic backup
on: 
  schedule:
  - cron: "33,35,38,40,45 3 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
      - name: install contentful cli
        run: npm install -g contentful-cli
      - name: export contentful data
        run: |
          export_date=`date +%Y-%m-%d_%H:%M:%S`
          contentful space export --config contentful/export-config.json --content-file "export_${export_date}.json"
      - name: commit data
        run: |
          git config --global user.email 2983604867@qq.com
          git config --global user.name zl-go
          git add .
          git commit -m "push the contenful backup file test" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
