name: contentful automic backup
run-name: contentful automic backup
on:
  schedule:
  - cron: "45 0 * * 1"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install contentful cli
        run: npm install -g contentful-cli
      - name: export data
        run: contentful space export --config export-config.json
