name: update dockerfile-compose

on: 
   workflow_dispatch

jobs:
  export:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
 
      - id: setup
        uses: actions/setup-node@v3.5.1
      
      - name: update
        run: |
          chmod +x ./test.sh
          ./test.sh
          
      - name: push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "push the contenful backup file"
           
